sudo: false
language: node_js

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

env:
  global:
    - NVS_VERSION=1.4.2
  matrix:
    - NODEJS_VERSION=node/4
    - NODEJS_VERSION=node/6
    - NODEJS_VERSION=node/8
    - NODEJS_VERSION=nightly
    - NODEJS_VERSION=rc
    - NODEJS_VERSION=canary
    - NODEJS_VERSION=chakracore
    - NODEJS_VERSION=chakracore-nightly

matrix:
  allow_failures:
    - env: NODEJS_VERSION=nightly
    - env: NODEJS_VERSION=canary
    - env: NODEJS_VERSION=chakracore
    - env: NODEJS_VERSION=chakracore-nightly

before_install:
  - git clone --branch v$NVS_VERSION --depth 1 https://github.com/jasongin/nvs ~/.nvs
  - . ~/.nvs/nvs.sh
  - nvs --version

  - nvs remote rc https://nodejs.org/download/rc/
  - nvs remote canary https://nodejs.org/download/v8-canary/

  - nvs add $NODEJS_VERSION
  - nvs use $NODEJS_VERSION
  - node --version
  - node -p process.arch
  - npm --version

install:
  - unset NVM_NODEJS_ORG_MIRROR
  - npm install

script:
  - npm run build
